### ISSUE TITLE
can't access a elevator controller while it's built into an elevator 

### ISSUE THREAD

**Issue by fireair** [Thutmose/Thut-Elevators#13]
I may be doing something wrong but in the manual it says on page 12 that you can put chests and controller blocks in an elevator just make sure the elevator face is turned on but when i right click on a floor  number it doesn't move is it supposed to work like i think it is or am i wrong?

**Comment by fireair** [comment]
btw this is 1.12.2

**Comment by Thutmose** [comment]
include a screenshot of the elevator you made?

**Comment by fireair** [comment]
sure
![2018-08-17_15 29 39](https://user-images.githubusercontent.com/31391039/44287438-7f251000-a232-11e8-9e28-8906a5ed2fea.png)
![2018-08-17_15 29 28](https://user-images.githubusercontent.com/31391039/44287439-7fbda680-a232-11e8-85c1-0dc59aa9adae.png)

**Comment by Thutmose** [comment]
that all panel is part of the elevator itself? if so, it should be connected. does it update when you right click the panel inside the elevator?

**Comment by fireair** [comment]
no it shows all buttons as white

**Comment by fireair** [comment]
and it is part of the elevator

**Comment by Thutmose** [comment]
it is working fine on my end, please also include what versions of thuttech, thutcore and forge you are using?

![image](https://user-images.githubusercontent.com/2363472/44288087-15f6ca00-a23d-11e8-8862-c9c89d30c921.png)

**Comment by fireair** [comment]
definitely not the latest ill update and see if that fixes it

**Comment by fireair** [comment]
that fixed it thank you much
btw the whole moving elevator idea is awesome

**Comment by Thutmose** [comment]
I am glad it is working now, IIRC it was broken for a few versions, you probably had one of those older ones
