### ISSUE TITLE
[Request/Suggestion] Alternate elevator mode

### ISSUE THREAD

**Issue by Majora-Luna** [Thutmose/Thut-Elevators#18]
Which can be toggled via config file (or control blocks if that wouldn't be a hassle) where instead of choosing a floor, when a player gets on an elevator, they get stuck/locked into it and can ascend or descend with jump and sneak. 
Dismounting/exiting is achieved with any of the WASD/movement inputs (bonus: the player is automatically unhooked from the elevator once it has reached a control block). The distance an elevator can move is still tied to control blocks as currently (where an elevator will stop once it is two blocks below a control block)

As an illustration, I am trying to recreate Zelda 2 in minecraft and would like controllable elevators like shown 8 seconds into this video: https://youtu.be/88Uo_VNDhck  

Thank you for reading, hope this is possible! (aka not a pain to code)

**Comment by JUMSAO** [comment]
Why does thutcore 1.7.10 doesn't exist if the thut mod is avaiable for 1.7.10??
can you make a versions pls??

**Comment by Majora-Luna** [comment]
You posted in an old repository, which is fine, but you also replied to a random thread posting a completely unrelated question lmao, you ding dong. I'm not the developer, but post your question here: 

https://github.com/Thutmose/Thut/issues

**Comment by JUMSAO** [comment]
Ok
