### ISSUE TITLE
Game crashed when setting elevator base 

### ISSUE THREAD

**Issue by YaraDada** [Thutmose/Thut-Elevators#19]
Game crashed when I tried setting the elevator base using the crafted elevator white thingie. Now it keeps crashing every time I try to get back on the server

![549C654B-EAB6-4A61-8BCF-A9AE720DD57B](https://user-images.githubusercontent.com/65462793/82127140-44eef680-97a9-11ea-9fd8-57b84ae0a01a.jpeg)

**Comment by Thutmose** [comment]
seems to be a result of version missmatching, will be fixed when thuttech updatesproperly.
