### ISSUE TITLE
Unintentional behaviour with redstone ++

### ISSUE THREAD

**Issue by Multi-Coder-24** [Thutmose/Thut-Elevators#20]
I have redstone++ mod installed and the tile entity can be moved by pistons. Aread you aware of this and can it be fixed. If not please add a note somewhere

**Comment by Thutmose** [comment]
I am not sure what you mean by this report, could you make a better explained one here: https://github.com/Thuts-Mods/ThutTech/issues, this git repository isn't used anymore
