### ISSUE TITLE
Shift/sneak for assignment makes it impossible to assign levels in creative mode while flying

### ISSUE THREAD

**Issue by mmehnert** [Thutmose/Thut-Elevators#4]
because as soon as shift is pressed, the position of the player changes.
Assigning a different key to sneak somehow removes the assigning function of the left shift key.

**Comment by Thutmose** [comment]
have you tried pressing ctrl and shift? iirc that prevents you from going down while flying.

**Comment by mmehnert** [comment]
Very nice! Thanks. I'm obviously not at wizard level yet... :-)
