### ISSUE TITLE
Can't interact with elevator through OpenComputers

### ISSUE THREAD

**Issue by Shazuli** [Thutmose/Thut-Elevators#8]
***Hi!***

I was building my elevator and was thinking of having it computer controlled as the book says it has support for. It did interact with the computer, but there are only three functions available:
`address`, `slot` and `type`. None of the other functions like: `setFloor(number)` or `getFloor(number)` was available. Am I missing something or do I need to plug into something else? It is the controller right?

![2017-10-15_16 01 24](https://user-images.githubusercontent.com/9884180/31585665-1cf1220a-b1c6-11e7-8d67-cf594f1c282e.png)

![2017-10-15_16 26 30](https://user-images.githubusercontent.com/9884180/31585667-26913160-b1c6-11e7-8fd5-9411825f0712.png)

**Comment by Thutmose** [comment]
The controller is the correct thing to plug into, I will look into this, I haven't tested the OC support for a while (it took OC a while to update) so something could easily have broken with it.  What versions are you using?

**Comment by Shazuli** [comment]
I'm using latest version of OpenComputers: `(OpenComputers-MC1.12.1-1.7.0+a4b865247)`, Thut's Core: `(thutcore-5.11.0)` and Thut's Tech `(thuttech-6.0.4)`.

**Comment by Thutmose** [comment]
ahh, I see the problem, I hadn't updated the callbacks to check for the lowercased modid for opencomputers, so it isn't activating the support

**Comment by Thutmose** [comment]
testing the fix now, will upload it if it works

**Comment by Thutmose** [comment]
fixed in 6.0.5.1 (6.0.5 and 6.0.5.1 are both flagged as 1.12.2/1.12.1)

![image](https://user-images.githubusercontent.com/2363472/31585963-7151e9ca-b198-11e7-9e73-66f855205efe.png)

**Comment by Shazuli** [comment]
Thanks! I'll go download it now.

**Comment by Thutmose** [comment]
it might take a little bit for it to be approved on curseforge, I will keep the issue open till then

**Comment by Shazuli** [comment]
Alright. I'll keep and eye open until then.

**Comment by Thutmose** [comment]
it is taking a while to approve, here it is in a zip to test. this is the same file I uploaded (take the jar out of the zip, had to be put in a zip to upload here) 
[thuttech-6.0.5.1.jar.zip](https://github.com/Thutmose/Thut-Elevators/files/1385562/thuttech-6.0.5.1.jar.zip)

**Comment by Shazuli** [comment]
Yup, it works like a charm now! Thanks!
